fmfi-svt/eprihlaska

eprihlaska/forms.py, eprihlaska/templates/study_programme.html
* Add dean's invitation letter to the first page (along with an
associated checkbox) and JS to handle the UX.
* Update list of study programmes.
=> forms: Update the first page

eprihlaska/consts.py
=> Updated study programme description.

eprihlaska/templates/final.html, eprihlaska/views.py
* Student is no longer asked to fill out admission_wavers page if dean_invitation_letter is checked.
=> update: Dean letter skip

eprihlaska/forms.py, eprihlaska/validators.py
=> update: Added validator for birth number

eprihlaska/__init__.py, eprihlaska/forms.py, eprihlaska/templates/further_personal_info.html, eprihlaska/validators.py
* added date validator
* replaced DateField with StringField for date_of_birth
Fixes: #8 
=> validators: Date validator

eprihlaska/consts.py, eprihlaska/forms.py
=> validators: Added grade validator

eprihlaska/validators.py
=> validators: Empty field is now valid for birth number

eprihlaska/forms.py, eprihlaska/validators.py
=> email_duplicate: Added validator for email duplicates

eprihlaska/forms.py
=> grade_validator: Grades are now optional

eprihlaska/templates/final.html, eprihlaska/views.py
=> variable_sym: Added variable symbol for those without birth number

eprihlaska/validators.py
* Validator now checks if birth date from birth number exists.
* Changed ValueError to ValidationError in DateValidator.
Fixes: #39
=> birth_no_validation: Added deeper birth number validation

eprihlaska/templates/application_form.html, eprihlaska/templates/grade_listing.html, eprihlaska/templates/index.html
According to Bootstrap documentation it does matter in which order you use meta tags
More on the topic here: https://getbootstrap.com/docs/3.3/getting-started/#template
=> Fix IE meta tags

eprihlaska/validators.py
=> Add message for empty field to BirthNoValidator and DateValidator.

eprihlaska/consts.py
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>
=> consts: fixed typo in GRADE_SECOND_YEAR

eprihlaska/models.py, init_db.py
* Make sure the `application_form` IDs start at 1300.
* Fixes #135
=> update: Ensure app form ID starts at 1300

eprihlaska/templates/intro.html
* Remove stray text from the intro page.
* Fixes #132
=> update: Cleanup intro

eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/templates/application_form.html, eprihlaska/templates/final.html, eprihlaska/views.py, translations/en/LC_MESSAGES/messages.po
* Add a `textarea` note field to the final application screen.
* Refactor `/submit_app` endpoint and incorporate its business logic
into `/final`.
* Recreate English translations.
* Fixes #134
=> add: Note to final application screen

eprihlaska/views.py
* Add constraints for `matura_mat_grade`.
* Fixes #139
=> add: Constraints for `matura_mat_grade`

eprihlaska/ais_utils.py, eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/templates/application_form.html, eprihlaska/templates/grade_listing_table.html, eprihlaska/views.py
* Add `grades_inf` to all appropraite places
* Fixes #133
=> add: `grades_inf`

eprihlaska/templates/admin_list.html, eprihlaska/views.py
* Add Admin interface for payment receipt.
* Fix a few issues with handling payment receipt.
* Refactor saving session to DB into a separate function.
=> add: Admin interface for payment receipt

eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/templates/application_form.html
* Add SCIO certificate number field that can be optionally filled in,
along with some description.
* Fixes #145
=> add: SCIO certificate number field

eprihlaska/ais_utils.py
=> ais_utils: Vinko's fix

eprihlaska/views.py
* Make sure the file gets written into before passing it to `pdftk`.
=> NamedTemporaryFile: manage file closing

eprihlaska/ais_utils.py, eprihlaska/forms.py, eprihlaska/views.py
* Make sure `SOC_CHM` is recognized as a competition. Fixes #156
* Make sure an application only moves to `printed` state when the PDF to
be returned is correctly generated. Fixes #157
=> fix: SOC_CHM and printed state

eprihlaska/templates/admin_impersonate_list.html, eprihlaska/views.py
* Add an ability to impersonate a user.
* Add an endpoint that lists all users and allows one to pick which one
should be impersonated.
=> add: Impersonate a user

eprihlaska/ais_utils.py, eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/templates/application_form.html, eprihlaska/views.py
* Remove the screen that asks the user to insert father/mother name.
* Remove it from the menu.
* Update the templates to reflect this as well.
=> update: Remove father/mother screen

eprihlaska/templates/application_form.html, eprihlaska/templates/final.html
* Update the price to 15 USD
* Rephrase a few texts.
=> update: Small cosmetic text changes

eprihlaska/forms.py, eprihlaska/templates/application_form.html, eprihlaska/templates/application_form_header.html
* DEFAULT_MATURA_YEAR in PDF form
* Copy in application_form
* Note moved to previous page
=> update: A few small updates

eprihlaska/data/obce.csv, eprihlaska/data/odbory.csv, eprihlaska/data/rodinne-stavy.csv, eprihlaska/data/skoly.csv, eprihlaska/data/staty.csv, eprihlaska/data/vzdelanie.csv, scripts/README.md, scripts/ciselnik_obce_to_csv.py, scripts/ciselnik_to_csv.py
* The new version of "ciselniky" is contained within a single .xlsx file
with various sheets as opposed to various .xlsx files with single
sheet.
* This commit updates the processing scripts to accomodate to this while
also making sure only the first 3 columns get skipped.
* Finally, it also updates the raw data extracted from this "ciselniky"
into the appropriate .csv files.
=> update: New version of "ciselniky"

eprihlaska/ais_utils.py, requirements.txt
* Fix wrongly processed AIS2 ops which caused many applications not to
be saveable to AIS2.
* Bump a few versions in `requirements.txt`
=> fix: Wrongly processed AIS2 ops

README.md
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>
=> readme: copy config-sample.py to config.py

eprihlaska/consts.py
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>
=> consts: texts for documents to be uploaded

eprihlaska/__init__.py, eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/templates/final.html, eprihlaska/views.py
* Add an /files/upload endpoint that is capable of attaching a file to
an application.
* Render attached files in the final screen of the application form.
* Clean up a few stary lines (mostly whitespace).
=> add: Files upload

eprihlaska/consts.py, eprihlaska/templates/final.html
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>
=> update: select box for document types

eprihlaska/ais_utils.py
* Ensure the AIS copy-over pipeline works even in cases when the
applicaiton itself has not beem submitted yet.
=> ais: Fix application not submitted yet

eprihlaska/ais_utils.py
* Previously it was enough to put a study programme abbreviation into
AIS for it to get filled in automatically. This is no longer the case
now, as for instance `FYZ` matches both `FYZ` and `FYZ/k`.
* This commit fixes the situation by automatically choosing the
pre-filled (first) option when such a dialog gets opened while filling
in the study programme.
* The PSC field in the dialog that chooses it in the address fileds has
changed position. This commit introduces a change that reflects this
situation.
=> fix: Study programme choice

eprihlaska/consts.py, eprihlaska/forms.py, eprihlaska/views.py
* Bump the CURRENT_MATURA_YEAR and DEFAULT_MATURA_YEAR to 2025
* Update the list of study programmes and their requirements.
* Add a note about grades to any fiels with grades.
=> add: Updates for 2025
